apiVersion: v1
kind: Pod
metadata:
  name: sample-resouce-only-limit
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: 1024Mi
          cpu: 500m
