apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-hpa-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
#  behavior:
#    scaleDown:
#      stabilizationWindowSeconds: 300
#      policies:
#        - periodSeconds: 15
#          type: Percent
#          value: 100
#    scaleUp:
#      stabilizationWindowSeconds: 0
#      policies:
#        - periodSeconds: 15
#          type: Percent
#          value: 100
#        - type: Pods
#          value: 4
#          periodSeconds: 15
#      selectPolicy: Max
