apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-hpa-app
  template:
    metadata:
      labels:
        app: sample-hpa-app
    spec:
      containers:
        - name: nginx
          image: amsy810/echo-nginx:v2.0
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 25m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  type: ClusterIP
  selector:
    app: sample-hpa-app
  ports:
    - port: 8080
      targetPort: 80
