apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-resize
spec:
  storageClassName: sample-storageclass-resize
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi