apiVersion: v1
kind: Pod
metadata:
  name: sample-node-affinity
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minikube-m02
        - weight: 1
          preference:
            matchExpressions:
              - key: undefined
                operator: In
                values:
                  - undefined
