apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-affinity-host
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: sample-app
